### ISSUE TITLE
stops at the end of the polyline

### ISSUE THREAD

**Issue by X-SLAYER** [ibrierley/line_animator#1]
hello nice work again but when I tested the package with different points sometimes the animation stuck at the end of the polyline in the middle of points and give this exception
```════════ Exception caught by animation library ═════════════════════════════════
The following _CastError was thrown while notifying listeners for AnimationController:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      MapState._handleMoveEmit
package:flutter_map/…/map/map.dart:215
#1      MapState.move
package:flutter_map/…/map/map.dart:306
#2      MapControllerImpl.move
package:flutter_map/…/map/map.dart:41
#3      _MyHomePageState.build.<anonymous closure>
package:map_test/main.dart:82
#4      _LineAnimatorState.startAnimation.<anonymous closure>
package:map_test/line_animator.dart:231
...
The AnimationController notifying listeners was: AnimationController#cdc47(▶ 0.000)

```

this is the polyline points that I used 
```dart
  List<LatLng> points = [
    LatLng(33.335925, 35.770396),
    LatLng(33.315701, 35.808957),
    LatLng(33.27487, 35.776635),
    LatLng(33.264701, 35.781176),
    LatLng(33.254232, 35.805005),
    LatLng(33.244861, 35.812491),
    LatLng(33.20407, 35.817638)
  ];
```

**Comment by ibrierley** [comment]
Thanks, is that when swapping in that point data in the example ?

**Comment by X-SLAYER** [comment]
after the pl that I made my problem was fixed the last two polylines was just ignored [#3](https://github.com/ibrierley/line_animator/pull/3)

**Comment by ibrierley** [comment]
Thanks, I think your PR looks good.

I'm just checking another oddity (my code), I think there is also a problem
with the line between the initial point and the interpolated point (until
it hits the 2nd full point). So I'll merge your PR, just be aware of that
issue until I get chance to take a proper look at that.

Many thanks,

Ian

**Comment by ibrierley** [comment]
I think I've fixed the first points not being animated as well if you wanted to test.
